server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://10.30.20.212:8635/cxjk_xspt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Cloud@kuw9d2d22
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      minimumIdle: 50
      maximumPoolSize: 100
      connectionTestQuery: select 1
  boot:
    admin:
      client:
        url: http://10.30.50.146:8082
  mvc:
    view:
      prefix: /
      suffix: .html


management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    logfile:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

properties:
  filepath: /mnt/program/apache-tomcat-8.5.32-business/webapps/tmpfile
  downloadpath: http://msp2.cxjk.com/tmpfile

